### ISSUE TITLE
Cannot list directories?

### ISSUE THREAD

**Issue by tiotrom** [sammacbeth/dat-fox-helper#13] opened 2019-11-21 21:31 UTC
Like for example this one dat://ca85cb3c20ad37649e72b274fc47be5586bd75815b7a90aa19de4a4e7e441908/ - it only shows the text "directory" but no content.

**Comment by sammacbeth** [comment] 2019-11-28 10:08
Duplicate of #9

**Closed by sammacbeth** 2019-11-28 10:08 UTC
